lib/crud_agentes_web/router.ex
defmodule CrudAgentesWeb.Router do
  use CrudAgentesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CrudAgentesWeb do
    pipe_through :browser

    get "/", PageController, :index
    # resources "/agents", AgentController
    get "/agents_length", AgentController, :get_count_agents
    get "/agents", AgentController, :index
    get "/agents/:id/edit", AgentController, :edit
    get "/agents/new", AgentController, :new
    get "/agents/:id", AgentController, :show
    post "/agents", AgentController, :create
    patch "/agents/:id", AgentController, :update
    put "/agents/:id", AgentController, :update
    delete "/agents/:id", AgentController, :delete

    get "/postal_codes", PostalCodeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrudAgentesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CrudAgentesWeb.Telemetry
    end
  end
end

lib/crud_agentes_web/controllers/postal_code_controller.ex
defmodule CrudAgentesWeb.PostalCodeController do
  use CrudAgentesWeb, :controller

  alias CrudAgentes.Catalogs

  def index(conn, %{"searching" => searching}) do
    match = Catalogs.get_municipality_state(searching)

    conn
    |> json(%{matches: match})
  end

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/crud_agentes_web/views/postal_code_view.ex
defmodule CrudAgentesWeb.PostalCodeView do
  use CrudAgentesWeb, :view
end

lib/crud_agentes_web/templates/postal_code/index.html.eex
<div id="vue-controller">
  <div class="row">
    <div class="col-12">
      <form class="input-group mb-3">
        <input type="text" v-model="searching" @input="typeSearch" ref="inSearch"
            placeholder="Escribe un código postal" class="form-control">
      </form>
    </div>
    <!-- <div class="col-12 mb-3">
        <button class="btn btn-primary w-100"
          @click="searchRequest()">Buscar</button>
    </div> -->
  </div>

  <div class="row" v-if="cpMatches.length !== 0">
    <div class="col-12">
      <h1>Lista de resultados</h1>
    </div>
    <div class="col-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">CP</th>
            <th scope="col">Municipio</th>
            <th scope="col">Estado</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="match in cpMatches">
            <td>{{ match.cp }}</td>
            <td>{{ match.municipio }}</td>
            <td>{{ match.estado }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  const INDEX_URL = "<%= Routes.postal_code_path(@conn, :index) %>";

  new Vue({
    el: '#vue-controller',
    data: {
        searching: "",
        cpMatches: [],
    },
    methods: {
      typeSearch: async function(event) {
          let response;

          if (this.$refs.inSearch.value.length === 0) {
            this.cpMatches = [];
            return
          }

          response = await axios.get(INDEX_URL, {
              params: {
                  searching: this.searching
              }
          });

          if (response.status === 200) {
              this.cpMatches = response.data.matches;
              console.log(response);
          } else {
              console.log(response);
          }
      }
    }
  });
</script>